spring.application.name=WellPass-Mananagement-System

# PostgreSQL datasource configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/wellpass_db
spring.datasource.username=postgres
spring.datasource.password=mbonyii
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT Configuration
jwt.secret=YourVerySecureSecretKeyForWellPassApplicationMustBeAtLeast256BitsLong
jwt.expiration=86400000
spring.session.store-type=none

# Logging
logging.level.org.springframework.web=DEBUG
logging.level.com.varol.WellPass_Mananagement_System.security=DEBUG

# Gmail SMTP configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=cedrickngabo03@gmail.com
spring.mail.password=vixt xgnw klxt cqvv
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true